This notebook prepares the predictions for the Pyraformer predictions

In [35]:
import numpy as np

In [36]:
pred = np.load("predictions_wind_24.npy")
true = np.load("trues_wind_24.npy")

In [32]:
test.shape

(212, 24, 1)

In [38]:
true.shape

(5088,)

In [21]:
true.shape

(212, 24, 1)

In [69]:
type(test[0][0])

numpy.ndarray

In [ ]:
test = np.load()

In [77]:
import torch

In [81]:
check = torch.from_numpy(test)
check2 = torch.from_numpy(test2)

In [80]:
check.shape[1]

14400

In [85]:
check.size(1)

14400

In [88]:
check2.size(0)

17420

In [83]:
check2.shape

torch.Size([17420, 5])

In [76]:
test[1]

array([[-7.96882356,  0.66666667,  0.91304348,  0.        ,  1.        ],
       [-7.39633476,  0.66666667,  0.95652174,  0.        ,  1.        ],
       [-4.27459142,  0.66666667,  1.        ,  0.        ,  1.        ],
       ...,
       [ 4.39564647,  0.33333333,  0.7826087 ,  0.72727273,  1.        ],
       [ 3.17175774,  0.33333333,  0.82608696,  0.72727273,  1.        ],
       [ 5.06802467,  0.33333333,  0.86956522,  0.72727273,  1.        ]])

In [74]:
test2[4]

array([-5.10041269,  0.83333333,  0.08695652,  0.        ,  0.        ])

In [70]:
type(test2[4])

numpy.void

In [40]:
test[0][720]

array([4.22029523, 0.5       , 0.17391304, 0.09090909, 0.        ])